### ISSUE TITLE
ArrayIndexOutOfBoundsException while parsing SVG tag...

### ISSUE THREAD

**Issue by marvkis** [attoparser/attoparser#10]
Hi,

i stumbled over an bug which is triggered while parsing an file with Thymeleaf 3.0 Beta1 which is using attoparser for parsing files.

I get following exception:

```Stacktrace
Caused by: java.lang.ArrayIndexOutOfBoundsException: 9
	at org.attoparser.select.SelectorElementBuffer.bufferElementInnerWhiteSpace(SelectorElementBuffer.java:320)
	at org.attoparser.select.BlockSelectorMarkupHandler.handleInnerWhiteSpace(BlockSelectorMarkupHandler.java:1363)
	at org.attoparser.AbstractChainedMarkupHandler.handleInnerWhiteSpace(AbstractChainedMarkupHandler.java:341)
	at org.attoparser.ParsingAttributeSequenceUtil.parseAttributeSequence(ParsingAttributeSequenceUtil.java:79)
	at org.attoparser.ParsingElementMarkupUtil.parseStandaloneElement(ParsingElementMarkupUtil.java:90)
	at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:706)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301)
```

It happens while it is parsing this Tag (which is within an embedded SVG element in the template):
```xml
  <linearGradient
       gradientTransform="matrix(0.717007,0.0257984,-0.0501168,1.39288,441.38885,-49.610358)"
       gradientUnits="userSpaceOnUse"
       id="linearGradient2236"
       inkscape:collect="always"
       x1="-59.621563"
       x2="248.66016"
       xlink:href="#linearGradient2230"
       y1="176.09546"
       y2="278.6629" />
```

This tag is indeed formatted the why shown here.
I think that there is an issue when extending the array within [SelectorElementBuffer.bufferElementInnerWhiteSpace(char[], int, int, int, int):297ff](https://github.com/attoparser/attoparser/blob/master/src/main/java/org/attoparser/select/SelectorElementBuffer.java#L297) - the array's for elementInnerWhiteSpaceBuffers, elementInnerWhiteSpaceLines and elementInnerWhiteSpaceCols are extended, but nut for elementInnerWhiteSpaceLens. Just a simple bug?

Thanks & Bye,
        marvkis

**Comment by danielfernandez** [comment]
Confirmed. Awesome bug reporting, thanks. Fortunately, it's really easy to fix :)

**Comment by danielfernandez** [comment]
Already in `2.0.0-SNAPSHOT` (used by current Thymeleaf `3.0.0-SNAPSHOT`)
