### ISSUE TITLE
Allow custom HTML elements with no suffix

### ISSUE THREAD

**Issue by danielfernandez** [attoparser/attoparser#17]
The HTML Custom Element Spec establishes that custom element names can exist with no suffix in their names, like `<whatever->`. AttoParser currently fails when trying to parse something like that, with:

```
Caused by: java.lang.IllegalArgumentException: Element name cannot be null
	at org.thymeleaf.engine.ElementName.<init>(ElementName.java:50)
	at org.thymeleaf.engine.HTMLElementName.<init>(HTMLElementName.java:77)
	at org.thymeleaf.engine.HTMLElementName.forName(HTMLElementName.java:64)
	at org.thymeleaf.engine.ElementNames.buildHTMLElementName(ElementNames.java:294)
```

See https://www.w3.org/TR/custom-elements/#valid-custom-element-name

Impact: thymeleaf/thymeleaf#570

**Comment by danielfernandez** [comment]
After evaluation, it seems AttoParser already does all it should, and it has no real issues with no-suffix tag names. All modifications to be done should be done at the Thymeleaf level therefore.

**Comment by prushforth** [comment]
The message "Element name cannot be null" seems to suggest that what comes after the hyphen can't be empty. At least judging by the Thymeleaf documentation which describes a custom element name as {prefix}-{name}. But, I will definitely trust your assessment :-). Thanks for your efforts!

**Comment by prushforth** [comment]
Also, I recall seeing the name attoparser  before that message in either the exception in the debugger or in the debug logs

**Comment by danielfernandez** [comment]
> Also, I recall seeing the name attoparser before that message in either the exception in the debugger or in the debug logs

That's because Thymeleaf 3 works as a processor of a stream of events, and those events are triggered by the parser (AttoParser). So the parser's markup handler always has to be one of the steps in the exception trace.

But AttoParser is having no problem with your trailing hyphens. It's definitely Thymeleaf who is not allowing them, so it's there where this should be evaluated.

**Comment by prushforth** [comment]
Thanks
